# FOR DEVELOPMENT USE ONLY
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/home/node/code
      - /home/node/code/node_modules
    environment:
      - VITE_API_GATEWAY=http://localhost:4000/api

  gateway-service:
    build: ./gateway-service
    networks:
      - app-network
      - auth-network
      - profile-network
    ports:
      - "4000:4000"
    volumes:
      - ./gateway-service:/home/golang/code
    depends_on:
      - auth-db
    environment:
      - PORT_NUMBER=4000
      - QUESTION_SERVICE_CONNECTION_STRING=http://question-service:3000
      - PROFILE_SERVICE_CONNECTION_STRING=http://profile-service:8080
      - FRONTEND_SERVICE_CONNECTION_STRING=http://localhost:5173
      - JWT_SECRET=honeypot
      - AUTH_DB_HOST=auth-db
      - AUTH_DB_NAME=auth
      - AUTH_DB_PORT_NUMBER=5432
      - AUTH_DB_USER=developer
      - AUTH_DB_PASSWORD=password

  auth-db:
    image: postgres:16-alpine
    networks:
      - auth-network
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/auth-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password

  question-service:
    build: ./question-service
    networks:
      - app-network
      - question-network
    ports:
      - "3000:3000"
    volumes:
      - ./question-service:/home/node/code
      - /home/node/code/node_modules
    depends_on:
      - question-service-db
    environment:
      - MONGO_CONNECTION_STRING=mongodb://dev:password@question-service-db:27017
      - FRONTEND_SERVICE_CONNECTION_STRING=http://localhost:5173

  question-service-db:
    image: mongo
    networks:
      - question-network
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./docker-data/question-service-db
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=password

  profile-service:
    build: ./profile-service
    networks:
      - profile-network
    ports:
      - "8080:8080"
    volumes:
      - ./profile-service:/home/spring/code
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://profile-service-db:5432/profile
      - SPRING_DATASOURCE_USERNAME=developer
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  profile-service-db:
    image: postgres:16-alpine
    networks:
      - profile-network
    ports:
      - "8000:5432"
    volumes:
      - ./docker-data/profile-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=profile
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password

networks:
  question-network:
    driver: bridge
  app-network:
    driver: bridge
  auth-network:
    driver: bridge
  profile-network:
    driver: bridge

volumes:
  question-service-db:
